(function(){const colors=['#070809','#2a0b0b','#000000','#1b1c1e'];const key='cyberbishop_bg_idx';let idx=parseInt(localStorage.getItem(key),10);idx=Number.isFinite(idx)?(idx+1)%colors.length:0;try{localStorage.setItem(key,idx)}catch{}document.documentElement.style.setProperty('--bg-color',colors[idx])})();
const {createClient}=window.supabase;const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);let DATA={categories:[],books:[],songs:[],videos:[],settings:null};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safe=v=>{try{const u=new URL(v,location.href);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}};
async function loadData(){const [c,b,s,v,set]=await Promise.all([db.from('categories').select('*').order('display_order').then(x=>x),db.from('books').select('*').eq('published',true).order('display_order'),db.from('songs').select('*').eq('published',true).order('display_order'),db.from('videos').select('*').eq('published',true).order('display_order'),db.from('site_settings').select('*').limit(1).maybeSingle()]);const err=[c,b,s,v,set].find(x=>x.error);if(err)throw err.error;DATA={categories:c.data||[],books:b.data||[],songs:s.data||[],videos:v.data||[],settings:set.data||null};return DATA}
function categorySlug(c){return (c.title||'category').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function categoryBySlug(slug){return DATA.categories.find(c=>categorySlug(c)===slug)}
function nav(){document.querySelectorAll('.nav-toggle').forEach(b=>b.onclick=()=>document.querySelector('.nav-links').classList.toggle('open'));const path=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-links a').forEach(a=>{if(a.getAttribute('href')===path)a.classList.add('active')});const s=document.querySelector('#globalSearch');if(s){s.onclick=()=>document.querySelector('.search-overlay')?.classList.add('open')}}
function motion(){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>obs.observe(x));document.querySelectorAll('.profile').forEach(c=>c.addEventListener('pointermove',e=>{const r=c.getBoundingClientRect();c.style.setProperty('--mx',`${((e.clientX-r.left)/r.width)*100}%`);c.style.setProperty('--my',`${((e.clientY-r.top)/r.height)*100}%`)}));const glow=document.querySelector('.cursor-glow');if(glow&&!matchMedia('(pointer:coarse)').matches){addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'})}}
function shell(active=''){document.querySelectorAll('[data-site-nav]').forEach(n=>n.innerHTML=`<header class="site-header"><div class="wrap nav"><a class="brand" href="index.html"><img class="brand-logo" src="assets/logo-icon.png" alt="Cyberbishop"><span>CYBER<span>BISHOP</span></span></a><nav class="nav-links"><a href="index.html">Home</a><a href="music.html">Music</a><a href="books.html">Books</a><a href="videos.html">Videos</a><a href="catalog.html">Catalog</a><a href="saved.html">Saved</a><a href="about.html">About</a><a class="nav-cta" href="connect.html">Connect</a></nav><button id="globalSearch" class="nav-search" aria-label="Search">⌕</button><button class="nav-toggle">☰</button></div></header><div class="search-overlay"><div class="search-panel"><button class="search-close">×</button><div class="section-tag">Explore the library</div><h2>Find your next <em>discovery.</em></h2><input id="globalSearchInput" class="search" placeholder="Search music, books, videos..."><div id="globalSearchResults" class="search-results"></div></div></div>`);nav();const ov=document.querySelector('.search-overlay');ov?.querySelector('.search-close')?.addEventListener('click',()=>ov.classList.remove('open'));ov?.addEventListener('click',e=>{if(e.target===ov)ov.classList.remove('open')});const inp=document.querySelector('#globalSearchInput');inp?.addEventListener('input',async()=>{const q=inp.value.trim().toLowerCase();const out=document.querySelector('#globalSearchResults');if(!q){out.innerHTML='<p class="muted">Start typing to search the library.</p>';return}try{const d=await loadData();let a=[...d.books.map(x=>[x,'book']),...d.songs.map(x=>[x,'song']),...d.videos.map(x=>[x,'video'])].filter(([x])=>(x.title+' '+(x.description||'')).toLowerCase().includes(q)).slice(0,8);out.innerHTML=a.length?a.map(([x,t])=>`<a class="search-result" href="item.html?type=${t}&id=${encodeURIComponent(x.id)}"><span>${t}</span><strong>${esc(x.title)}</strong><small>${esc(x.description||'')}</small></a>`).join(''):'<p class="muted">Nothing found yet.</p>'}catch(e){out.innerHTML='<p class="muted">Search is temporarily unavailable.</p>'}})}
function footer(){const el=document.querySelector('[data-site-footer]');if(el)el.innerHTML=`<footer class="footer"><div class="wrap footer-grid"><div class="footer-brand"><img class="footer-logo" src="assets/logo-icon.png" alt="Cyberbishop"><div><strong style="color:#fff">CYBERBISHOP</strong><div>Faith · Identity · Christ</div></div></div><div class="footer-links"><a href="music.html">Music</a><a href="books.html">Books</a><a href="videos.html">Videos</a><a href="catalog.html">Catalog</a><a href="saved.html">Saved</a><a href="connect.html">Connect</a></div></div></footer>`}
function mediaCard(item,type){const id=encodeURIComponent(item.id);let thumb=(item.cover_image_url||item.thumbnail_url)?`<img src="${esc(safe(item.cover_image_url||item.thumbnail_url))}" alt="" loading="lazy">`:(type==='video'?`<div class="play">▶</div>`:`<span style="font-size:40px">${type==='song'?'♫':'✦'}</span>`);let action=type==='video'?`<button class="btn btn-primary video-open" data-video="${esc(safe(item.video_url))}">Watch video →</button>`:`<a class="btn" href="${esc(safe(type==='song'?item.spotify_url:item.purchase_url))}" target="_blank" rel="noopener">${esc(item.link_label||'Open')} →</a>`;const cat=DATA.categories.find(c=>c.id===item.category_id);const catPill=cat?`<a class="pill pill-cat" href="category.html?slug=${encodeURIComponent(categorySlug(cat))}">${esc(cat.title)}</a>`:'';return `<article class="media-card reveal" data-id="${esc(item.id)}"><a class="media-thumb-link" href="item.html?type=${type}&id=${id}"><div class="media-thumb">${thumb}</div></a><span class="pill">${type}</span>${catPill}<h3><a href="item.html?type=${type}&id=${id}">${esc(item.title)}</a></h3><p>${esc(item.description||'')}</p><div class="card-actions"><a class="btn btn-ghost" href="item.html?type=${type}&id=${id}">Explore →</a>${action}<button class="btn review-open" data-review-type="${type}" data-review-id="${esc(item.id)}" data-review-title="${esc(item.title)}">★ Reviews</button></div><button class="save-btn" data-save-type="${type}" data-save-id="${esc(item.id)}" aria-label="Save ${esc(item.title)}">♡</button></article>`}
function renderList(container,items,type){container.innerHTML=items.length?items.map(x=>mediaCard(x,type)).join(''):`<div class="empty">No published ${type} yet. Add it from the CMS.</div>`;bindVideos();bindSaves();bindReviews();motion()}
function bindVideos(){document.querySelectorAll('.video-open').forEach(b=>b.onclick=()=>{const m=document.querySelector('.video-modal');const v=m.querySelector('video');v.poster=b.dataset.poster||'';v.src=b.dataset.video;m.classList.add('open');v.play().catch(()=>{})})}
function setupModal(){const m=document.querySelector('.video-modal');if(!m)return;const close=()=>{const v=m.querySelector('video');v.pause();v.removeAttribute('src');v.load();m.classList.remove('open')};m.querySelector('.close').onclick=close;m.onclick=e=>{if(e.target===m)close()};document.addEventListener('keydown',e=>e.key==='Escape'&&close())}
// --- Reviews / testimonials ---
function renderStars(n,size='16px'){n=Math.max(0,Math.min(5,Math.round(n||0)));let out='';for(let i=1;i<=5;i++)out+=`<span style="color:${i<=n?'var(--gold)':'var(--line)'};font-size:${size}">★</span>`;return out}
async function loadReviews(targetType,targetId){let q=db.from('reviews').select('*').eq('target_type',targetType).eq('approved',true).order('created_at',{ascending:false});q=targetType==='site'?q.is('target_id',null):q.eq('target_id',targetId);const {data,error}=await q;if(error)throw error;return data||[]}
async function submitReview(targetType,targetId,name,rating,comment){const cleanName=(name||'').trim();const cleanComment=(comment||'').trim();if(!cleanName)throw new Error('Please enter your name.');if(!Number.isInteger(Number(rating))||Number(rating)<1||Number(rating)>5)throw new Error('Please select a rating from 1 to 5 stars.');const payload={target_type:targetType,target_id:targetType==='site'?null:targetId,reviewer_name:cleanName,rating:Number(rating),comment:cleanComment||null,approved:false};const {error}=await db.from('reviews').insert(payload);if(error){if(error.code==='42501')throw new Error('Reviews are temporarily unavailable. Please try again later.');if(error.code==='PGRST204')throw new Error('The reviews database is out of sync. Please contact the site administrator.');throw error}return true}
function reviewsListHTML(list){if(!list.length)return `<div class="empty">No reviews yet. Be the first to share one.</div>`;return list.map(r=>`<div class="review-item"><div class="review-item-top"><strong>${esc(r.reviewer_name)}</strong><span class="review-stars">${renderStars(r.rating,'13px')}</span></div>${r.comment?`<p>${esc(r.comment)}</p>`:''}</div>`).join('')}
function reviewFormHTML(formId){return `<form id="${formId}" class="review-form"><div class="field"><label>Your name</label><input class="rf-name" required></div><div class="field"><label>Rating</label><div class="star-picker" data-value="5">${[1,2,3,4,5].map(i=>`<span data-star="${i}" class="star-pick on">★</span>`).join('')}</div></div><div class="field"><label>Your review</label><textarea class="rf-comment" rows="3"></textarea></div><button class="btn btn-primary" type="submit">Submit review</button><div class="hint rf-status"></div></form>`}
function wireStarPicker(root){const picker=root.querySelector('.star-picker');if(!picker)return;const stars=[...picker.querySelectorAll('.star-pick')];const paint=v=>stars.forEach(s=>s.classList.toggle('on',Number(s.dataset.star)<=v));stars.forEach(s=>s.onclick=()=>{picker.dataset.value=s.dataset.star;paint(Number(s.dataset.star))});paint(5)}
function wireReviewForm(root,targetType,targetId,onSubmitted){const form=root.querySelector('.review-form');if(!form)return;wireStarPicker(root);form.onsubmit=async e=>{e.preventDefault();const status=root.querySelector('.rf-status');const name=root.querySelector('.rf-name').value;const rating=root.querySelector('.star-picker').dataset.value;const comment=root.querySelector('.rf-comment').value;try{status.textContent='Submitting…';await submitReview(targetType,targetId,name,rating,comment);form.reset();wireStarPicker(root);status.textContent='Thanks! Your review is awaiting approval.';if(onSubmitted)onSubmitted()}catch(err){status.textContent=err.message}}}
async function openReviewModal(type,id,title){const m=document.querySelector('.review-modal');if(!m)return;m.querySelector('.review-modal-title').textContent=`${title} — Reviews`;const list=m.querySelector('.review-list');list.innerHTML='<div class="empty">Loading reviews…</div>';m.classList.add('open');try{const reviews=await loadReviews(type,id);list.innerHTML=reviewsListHTML(reviews)}catch(err){list.innerHTML=`<div class="empty">${esc(err.message)}</div>`}const formHost=m.querySelector('.review-form-host');formHost.innerHTML=reviewFormHTML('mediaReviewForm');wireReviewForm(formHost,type,id)}
function bindReviews(){document.querySelectorAll('.review-open').forEach(b=>b.onclick=()=>openReviewModal(b.dataset.reviewType,b.dataset.reviewId,b.dataset.reviewTitle))}
function setupReviewModal(){const m=document.querySelector('.review-modal');if(!m)return;const close=()=>m.classList.remove('open');m.querySelector('.close').onclick=close;m.onclick=e=>{if(e.target===m)close()};document.addEventListener('keydown',e=>e.key==='Escape'&&close())}
const HERO_IMAGES=['assets/hero/bishop-1.jpg','assets/hero/bishop-2.jpg'];
function paintPhotoHero(){document.querySelectorAll('.photo-hero').forEach(el=>{const src=HERO_IMAGES[Math.floor(Math.random()*HERO_IMAGES.length)];el.style.setProperty('--hero-img',`url(${src})`)})}
function common(){shell();footer();setupModal();setupReviewModal();paintPhotoHero();logVisit();initChatWidget();}
// --- Visitor logging ---
function logVisit(){try{if(sessionStorage.getItem('cyberbishop_visit_logged'))return;sessionStorage.setItem('cyberbishop_visit_logged','1');db.from('visits').insert({page:location.pathname.split('/').pop()||'index.html',referrer:document.referrer||null,user_agent:navigator.userAgent||null}).then(()=>{}).catch(()=>{})}catch{}}
// --- AI chat widget ---
function chatHistory(){try{return JSON.parse(sessionStorage.getItem('cyberbishop_chat_msgs')||'[]')}catch{return []}}
function saveChatHistory(list){try{sessionStorage.setItem('cyberbishop_chat_msgs',JSON.stringify(list.slice(-30)))}catch{}}
const CHAT_WELCOMES=["Hey there! Welcome to Cyberbishop 👋 I can help you find music, books, or videos here — what are you in the mood for?","Welcome! Glad you stopped by Cyberbishop. Ask me about the music, books, or videos on the site, or anything else on your mind.","Hi! Thanks for visiting Cyberbishop. Looking for something specific — music, books, videos — or just browsing? I'm happy to help either way."];
function chatBubbleHTML(role,text){return `<div class="chat-msg chat-msg-${role}">${esc(text)}</div>`}
function renderChat(){const list=document.querySelector('#chatMessages');if(!list)return;const hist=chatHistory();list.innerHTML=hist.map(m=>chatBubbleHTML(m.role,m.content)).join('');list.scrollTop=list.scrollHeight}
async function sendChatMessage(text){const hist=chatHistory();hist.push({role:'user',content:text});saveChatHistory(hist);renderChat();const list=document.querySelector('#chatMessages');const typing=document.createElement('div');typing.className='chat-msg chat-msg-assistant chat-typing';typing.textContent='…';list?.appendChild(typing);list.scrollTop=list.scrollHeight;try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:hist})});const data=await r.json();typing.remove();const reply=data.reply||data.error||"Sorry, I'm having trouble responding right now.";const hist2=chatHistory();hist2.push({role:'assistant',content:reply});saveChatHistory(hist2);renderChat()}catch(err){typing.remove();const hist2=chatHistory();hist2.push({role:'assistant',content:"Sorry, I'm having trouble connecting right now — please try again in a moment."});saveChatHistory(hist2);renderChat()}}
function initChatWidget(){if(document.querySelector('.chat-widget'))return;const wrap=document.createElement('div');wrap.className='chat-widget';wrap.innerHTML=`<button class="chat-fab" aria-label="Chat with us">💬</button><div class="chat-panel"><div class="chat-panel-head"><strong>Cyberbishop Assistant</strong><button class="chat-close" aria-label="Close chat">×</button></div><div id="chatMessages" class="chat-messages"></div><form id="chatForm" class="chat-form"><input id="chatInput" autocomplete="off" placeholder="Type a message…" required><button type="submit" aria-label="Send">➤</button></form></div>`;document.body.appendChild(wrap);const panel=wrap.querySelector('.chat-panel');const open=()=>{panel.classList.add('open');renderChat();wrap.querySelector('#chatInput')?.focus()};wrap.querySelector('.chat-fab').onclick=()=>panel.classList.contains('open')?panel.classList.remove('open'):open();wrap.querySelector('.chat-close').onclick=()=>panel.classList.remove('open');wrap.querySelector('#chatForm').onsubmit=e=>{e.preventDefault();const inp=wrap.querySelector('#chatInput');const val=inp.value.trim();if(!val)return;inp.value='';sendChatMessage(val)};
if(!chatHistory().length){const welcome=CHAT_WELCOMES[Math.floor(Math.random()*CHAT_WELCOMES.length)];saveChatHistory([{role:'assistant',content:welcome}])}
if(!sessionStorage.getItem('cyberbishop_chat_greeted')){sessionStorage.setItem('cyberbishop_chat_greeted','1');setTimeout(open,1400)}
}

function getAllItems(){return [...DATA.books.map(x=>({...x,_type:'book'})),...DATA.songs.map(x=>({...x,_type:'song'})),...DATA.videos.map(x=>({...x,_type:'video'}))]}
function saveKey(t,id){return `${t}:${id}`}
function getSaved(){try{return JSON.parse(localStorage.getItem('cyberbishop_saved')||'[]')}catch{return[]}}
function toggleSaved(t,id){let a=getSaved(),k=saveKey(t,id);a=a.includes(k)?a.filter(x=>x!==k):[...a,k];localStorage.setItem('cyberbishop_saved',JSON.stringify(a));return a.includes(k)}
function bindSaves(){document.querySelectorAll('.save-btn').forEach(b=>{const saved=getSaved().includes(saveKey(b.dataset.saveType,b.dataset.saveId));b.textContent=saved?'♥':'♡';b.classList.toggle('saved',saved);b.onclick=()=>{const now=toggleSaved(b.dataset.saveType,b.dataset.saveId);b.textContent=now?'♥':'♡';b.classList.toggle('saved',now)}})}
function remember(type,id){try{let a=JSON.parse(localStorage.getItem('cyberbishop_recent')||'[]').filter(x=>!(x.type===type&&x.id===id));a.unshift({type,id,at:Date.now()});localStorage.setItem('cyberbishop_recent',JSON.stringify(a.slice(0,12)))}catch{}}
