const {createClient}=window.supabase;const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);let DATA={categories:[],books:[],songs:[],videos:[],settings:null};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safe=v=>{try{const u=new URL(v,location.href);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}};
async function loadData(){const [c,b,s,v,set]=await Promise.all([db.from('categories').select('*').order('display_order').then(x=>x),db.from('books').select('*').eq('published',true).order('display_order'),db.from('songs').select('*').eq('published',true).order('display_order'),db.from('videos').select('*').eq('published',true).order('display_order'),db.from('site_settings').select('*').limit(1).maybeSingle()]);const err=[c,b,s,v,set].find(x=>x.error);if(err)throw err.error;DATA={categories:c.data||[],books:b.data||[],songs:s.data||[],videos:v.data||[],settings:set.data||null};return DATA}
function categorySlug(c){return (c.title||'category').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function categoryBySlug(slug){return DATA.categories.find(c=>categorySlug(c)===slug)}
function nav(){document.querySelectorAll('.nav-toggle').forEach(b=>b.onclick=()=>document.querySelector('.nav-links').classList.toggle('open'));const path=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-links a').forEach(a=>{if(a.getAttribute('href')===path)a.classList.add('active')});const s=document.querySelector('#globalSearch');if(s){s.onclick=()=>document.querySelector('.search-overlay')?.classList.add('open')}}
function motion(){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>obs.observe(x));document.querySelectorAll('.profile').forEach(c=>c.addEventListener('pointermove',e=>{const r=c.getBoundingClientRect();c.style.setProperty('--mx',`${((e.clientX-r.left)/r.width)*100}%`);c.style.setProperty('--my',`${((e.clientY-r.top)/r.height)*100}%`)}));const glow=document.querySelector('.cursor-glow');if(glow&&!matchMedia('(pointer:coarse)').matches){addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'})}}
function shell(active=''){document.querySelectorAll('[data-site-nav]').forEach(n=>n.innerHTML=`<header class="site-header"><div class="wrap nav"><a class="brand" href="index.html"><span class="brand-mark">✦</span><span>CYBER<span>BISHOP</span></span></a><nav class="nav-links"><a href="index.html">Home</a><a href="music.html">Music</a><a href="books.html">Books</a><a href="videos.html">Videos</a><a href="catalog.html">Catalog</a><a href="saved.html">Saved</a><a href="about.html">About</a><a class="nav-cta" href="connect.html">Connect</a></nav><button id="globalSearch" class="nav-search" aria-label="Search">⌕</button><button class="nav-toggle">☰</button></div></header><div class="search-overlay"><div class="search-panel"><button class="search-close">×</button><div class="section-tag">Explore the library</div><h2>Find your next <em>discovery.</em></h2><input id="globalSearchInput" class="search" placeholder="Search music, books, videos..."><div id="globalSearchResults" class="search-results"></div></div></div>`);nav();const ov=document.querySelector('.search-overlay');ov?.querySelector('.search-close')?.addEventListener('click',()=>ov.classList.remove('open'));ov?.addEventListener('click',e=>{if(e.target===ov)ov.classList.remove('open')});const inp=document.querySelector('#globalSearchInput');inp?.addEventListener('input',async()=>{const q=inp.value.trim().toLowerCase();const out=document.querySelector('#globalSearchResults');if(!q){out.innerHTML='<p class="muted">Start typing to search the library.</p>';return}try{const d=await loadData();let a=[...d.books.map(x=>[x,'book']),...d.songs.map(x=>[x,'song']),...d.videos.map(x=>[x,'video'])].filter(([x])=>(x.title+' '+(x.description||'')).toLowerCase().includes(q)).slice(0,8);out.innerHTML=a.length?a.map(([x,t])=>`<a class="search-result" href="item.html?type=${t}&id=${encodeURIComponent(x.id)}"><span>${t}</span><strong>${esc(x.title)}</strong><small>${esc(x.description||'')}</small></a>`).join(''):'<p class="muted">Nothing found yet.</p>'}catch(e){out.innerHTML='<p class="muted">Search is temporarily unavailable.</p>'}})}
function footer(){const el=document.querySelector('[data-site-footer]');if(el)el.innerHTML=`<footer class="footer"><div class="wrap footer-grid"><div><strong style="color:#fff">CYBERBISHOP</strong><div>Faith · Identity · Christ</div></div><div class="footer-links"><a href="music.html">Music</a><a href="books.html">Books</a><a href="videos.html">Videos</a><a href="catalog.html">Catalog</a><a href="saved.html">Saved</a><a href="connect.html">Connect</a></div></div></footer>`}
function mediaCard(item,type){const id=encodeURIComponent(item.id);let thumb=(item.cover_image_url||item.thumbnail_url)?`<img src="${esc(safe(item.cover_image_url||item.thumbnail_url))}" alt="" loading="lazy">`:(type==='video'?`<div class="play">▶</div>`:`<span style="font-size:40px">${type==='song'?'♫':'✦'}</span>`);let action=type==='video'?`<button class="btn btn-primary video-open" data-video="${esc(safe(item.video_url))}">Watch video →</button>`:`<a class="btn" href="${esc(safe(type==='song'?item.spotify_url:item.purchase_url))}" target="_blank" rel="noopener">${esc(item.link_label||'Open')} →</a>`;const cat=DATA.categories.find(c=>c.id===item.category_id);const catPill=cat?`<a class="pill pill-cat" href="category.html?slug=${encodeURIComponent(categorySlug(cat))}">${esc(cat.title)}</a>`:'';return `<article class="media-card reveal" data-id="${esc(item.id)}"><a class="media-thumb-link" href="item.html?type=${type}&id=${id}"><div class="media-thumb">${thumb}</div></a><span class="pill">${type}</span>${catPill}<h3><a href="item.html?type=${type}&id=${id}">${esc(item.title)}</a></h3><p>${esc(item.description||'')}</p><div class="card-actions"><a class="btn btn-ghost" href="item.html?type=${type}&id=${id}">Explore →</a>${action}</div><button class="save-btn" data-save-type="${type}" data-save-id="${esc(item.id)}" aria-label="Save ${esc(item.title)}">♡</button></article>`}
function renderList(container,items,type){container.innerHTML=items.length?items.map(x=>mediaCard(x,type)).join(''):`<div class="empty">No published ${type} yet. Add it from the CMS.</div>`;bindVideos();bindSaves();motion()}
function bindVideos(){document.querySelectorAll('.video-open').forEach(b=>b.onclick=()=>{const m=document.querySelector('.video-modal');const v=m.querySelector('video');v.poster=b.dataset.poster||'';v.src=b.dataset.video;m.classList.add('open');v.play().catch(()=>{})})}
function setupModal(){const m=document.querySelector('.video-modal');if(!m)return;const close=()=>{const v=m.querySelector('video');v.pause();v.removeAttribute('src');v.load();m.classList.remove('open')};m.querySelector('.close').onclick=close;m.onclick=e=>{if(e.target===m)close()};document.addEventListener('keydown',e=>e.key==='Escape'&&close())}
function common(){shell();footer();setupModal();}

function getAllItems(){return [...DATA.books.map(x=>({...x,_type:'book'})),...DATA.songs.map(x=>({...x,_type:'song'})),...DATA.videos.map(x=>({...x,_type:'video'}))]}
function saveKey(t,id){return `${t}:${id}`}
function getSaved(){try{return JSON.parse(localStorage.getItem('cyberbishop_saved')||'[]')}catch{return[]}}
function toggleSaved(t,id){let a=getSaved(),k=saveKey(t,id);a=a.includes(k)?a.filter(x=>x!==k):[...a,k];localStorage.setItem('cyberbishop_saved',JSON.stringify(a));return a.includes(k)}
function bindSaves(){document.querySelectorAll('.save-btn').forEach(b=>{const saved=getSaved().includes(saveKey(b.dataset.saveType,b.dataset.saveId));b.textContent=saved?'♥':'♡';b.classList.toggle('saved',saved);b.onclick=()=>{const now=toggleSaved(b.dataset.saveType,b.dataset.saveId);b.textContent=now?'♥':'♡';b.classList.toggle('saved',now)}})}
function remember(type,id){try{let a=JSON.parse(localStorage.getItem('cyberbishop_recent')||'[]').filter(x=>!(x.type===type&&x.id===id));a.unshift({type,id,at:Date.now()});localStorage.setItem('cyberbishop_recent',JSON.stringify(a.slice(0,12)))}catch{}}
